import os
import nltk
from collections import defaultdict

# Setup directories
script_dir = os.path.dirname(os.path.abspath(__file__))
output_file = os.path.join(script_dir, "..", "src", "ModernNotepad.Core", "Analysis", "GrammarLexicon.g.cs")

# Download necessary datasets
print("Downloading NLTK datasets (brown, universal_tagset)...")
nltk.download('brown', quiet=True)
nltk.download('universal_tagset', quiet=True)

print("Processing Brown corpus...")
# Brown corpus provides sentences tagged with POS
tagged_words = nltk.corpus.brown.tagged_words(tagset='universal')

# We'll map (word) -> (dict of POS -> count)
word_pos_counts = defaultdict(lambda: defaultdict(int))

# Also keep an overall frequency count
word_freq = defaultdict(int)

for word, tag in tagged_words:
    word_lower = word.lower()
    # Basic filter: only alphabetic words
    if not word_lower.isalpha():
        continue
    
    word_freq[word_lower] += 1
    word_pos_counts[word_lower][tag] += 1

# Sort words by frequency, take top 15000 to ensure we have a massive high quality list
top_words = sorted(word_freq.items(), key=lambda x: x[1], reverse=True)[:15000]

# Mapping from NLTK Universal Tag to our GrammarCategory enum
tag_map = {
    'NOUN': 'GrammarCategory.ObjectNoun',
    'VERB': 'GrammarCategory.Verb',
    'ADJ': 'GrammarCategory.Adjective',
    'ADV': 'GrammarCategory.Adverb',
    'PRON': 'GrammarCategory.Pronoun',
    'ADP': 'GrammarCategory.Preposition',
    'CONJ': 'GrammarCategory.Conjunction',
    'DET': 'GrammarCategory.Determiner'
}

print("Generating C# dictionary...")
entries = []

for word, freq in top_words:
    pos_counts = word_pos_counts[word]
    # find the most frequent POS for this word
    best_tag = max(pos_counts.items(), key=lambda x: x[1])[0]
    
    # Check if we map it
    if best_tag in tag_map:
        category = tag_map[best_tag]
        # C# format: { "word", GrammarCategory.XYZ }
        entries.append(f'        {{ "{word}", {category} }}')

# Write C# file
cs_content = f"""// <auto-generated>
// This file is auto-generated by scripts/generate_lexicon.py.
// Do not modify manually.
// </auto-generated>

using System.Collections.Generic;
using System;

namespace ModernNotepad.Core.Analysis;

public static class GrammarLexicon
{{
    public static readonly Dictionary<string, GrammarCategory> Lexicon = new(StringComparer.OrdinalIgnoreCase)
    {{
{",\n".join(entries)}
    }};
}}
"""

os.makedirs(os.path.dirname(output_file), exist_ok=True)
with open(output_file, 'w', encoding='utf-8') as f:
    f.write(cs_content)

print(f"Generated Lexicon with {len(entries)} words at: {os.path.abspath(output_file)}")
