// <auto-generated>
// Generated by scripts/generate_lexicon.py from WordNet 3.0 and Brown.
// Do not edit by hand. See THIRD_PARTY_NOTICES.md for data attribution.
// </auto-generated>

using System.Globalization;
using System.IO.Compression;
using System.Numerics;

namespace ModernNotepad.Core.Analysis;

[Flags]
internal enum LexiconTag : ushort
{
    None = 0,
    Noun = 1 << 0,
    Verb = 1 << 1,
    Adjective = 1 << 2,
    Adverb = 1 << 3,
    Pronoun = 1 << 4,
    Preposition = 1 << 5,
    Conjunction = 1 << 6,
    Determiner = 1 << 7,
    Particle = 1 << 8,
    Quantifier = 1 << 9
}

internal readonly record struct LexiconProfile(LexiconTag Tags, ulong PackedWeights)
{
    public int GetWeight(LexiconTag tag)
    {
        if (tag == LexiconTag.None || (Tags & tag) == 0)
        {
            return 0;
        }
        var index = BitOperations.TrailingZeroCount((uint)tag);
        return (int)((PackedWeights >> (index * 4)) & 0xFUL);
    }
}

/// <summary>
/// Offline English lexicon generated from WordNet and the Brown corpus.
/// The legacy <see cref="Lexicon"/> field remains source-compatible.
/// </summary>
public static class GrammarLexicon
{
    private const string ResourceName =
        "ModernNotepad.Core.Analysis.Data.GrammarLexicon.tsv.gz";

    public const int GeneratedWordCount = 108_845;
    public const int GeneratedAmbiguousWordCount = 11_314;
    public const string GeneratedAssetSha256 = "d6bb00754d7107aee080638982160a87a32aa0a65dd705392e8731c00b50b03c";
    public static readonly Dictionary<string, GrammarCategory> Lexicon;
    private static readonly Dictionary<string, LexiconProfile> AmbiguousProfiles;

    static GrammarLexicon()
    {
        Lexicon = new Dictionary<string, GrammarCategory>(
            GeneratedWordCount, StringComparer.OrdinalIgnoreCase);
        AmbiguousProfiles = new Dictionary<string, LexiconProfile>(
            GeneratedAmbiguousWordCount, StringComparer.OrdinalIgnoreCase);

        using var compressed = typeof(GrammarLexicon).Assembly
            .GetManifestResourceStream(ResourceName)
            ?? throw new InvalidOperationException(
                $"Embedded grammar lexicon '{ResourceName}' was not found.");
        using var gzip = new GZipStream(compressed, CompressionMode.Decompress);
        using var reader = new StreamReader(gzip);
        while (reader.ReadLine() is { } line)
        {
            var firstTab = line.IndexOf('	');
            var secondTab = line.IndexOf('	', firstTab + 1);
            var thirdTab = line.IndexOf('	', secondTab + 1);
            if (firstTab <= 0 || secondTab <= firstTab || thirdTab <= secondTab)
            {
                throw new InvalidDataException("The embedded grammar lexicon is malformed.");
            }
            var word = line[..firstTab];
            var category = (GrammarCategory)int.Parse(
                line.AsSpan(firstTab + 1, secondTab - firstTab - 1),
                NumberStyles.None, CultureInfo.InvariantCulture);
            var tags = (LexiconTag)ushort.Parse(
                line.AsSpan(secondTab + 1, thirdTab - secondTab - 1),
                NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture);
            var weights = ulong.Parse(
                line.AsSpan(thirdTab + 1),
                NumberStyles.AllowHexSpecifier, CultureInfo.InvariantCulture);

            Lexicon.Add(word, category);
            var bits = (ushort)tags;
            if ((bits & (bits - 1)) != 0)
            {
                AmbiguousProfiles.Add(word, new LexiconProfile(tags, weights));
            }
        }
        if (Lexicon.Count != GeneratedWordCount)
        {
            throw new InvalidDataException(
                $"Expected {GeneratedWordCount:N0} grammar words but loaded {Lexicon.Count:N0}.");
        }
    }

    internal static bool TryGetProfile(string word, out LexiconProfile profile)
    {
        if (AmbiguousProfiles.TryGetValue(word, out profile))
        {
            return true;
        }
        if (!Lexicon.TryGetValue(word, out var category))
        {
            profile = default;
            return false;
        }
        var tag = category switch
        {
            GrammarCategory.SubjectNoun or GrammarCategory.ObjectNoun => LexiconTag.Noun,
            GrammarCategory.Verb => LexiconTag.Verb,
            GrammarCategory.Adjective => LexiconTag.Adjective,
            GrammarCategory.Adverb => LexiconTag.Adverb,
            GrammarCategory.Pronoun => LexiconTag.Pronoun,
            GrammarCategory.Preposition => LexiconTag.Preposition,
            GrammarCategory.Conjunction => LexiconTag.Conjunction,
            GrammarCategory.Determiner => LexiconTag.Determiner,
            GrammarCategory.Particle => LexiconTag.Particle,
            GrammarCategory.Quantifier => LexiconTag.Quantifier,
            _ => LexiconTag.None
        };
        profile = new LexiconProfile(
            tag,
            tag == LexiconTag.None
                ? 0
                : 15UL << (BitOperations.TrailingZeroCount((uint)tag) * 4));
        return tag != LexiconTag.None;
    }
}
